#ifndef MapBehavior
#define MapBehavior
#define IMAGE_HEIGHT 240
#define IMAGE_WIDTH 320
#include <motionAuxiliarFunctions.hpp>
#include <ledAuxiliarFunctions.hpp>
#include <Align.hpp>
#include <AlignGoal.hpp>
#include <Avoid.hpp>
#include <BallClose.hpp>
#include <BehaviorBase.hpp>
#include <FollowBallGoalie.hpp>
#include <GmCtrlFinished.hpp>
#include <GmCtrlInitial.hpp>
#include <GmCtrlPenalized.hpp>
#include <GmCtrlPlaying.hpp>
#include <GmCtrlReady.hpp>
#include <GmCtrlSet.hpp>
#include <Kick.hpp>
#include <LookAround.hpp>
#include <LookForBall.hpp>
#include <Sonar.hpp>
#include <Start.hpp>
#include <TestBehavior.hpp>
#include <WalkInit.hpp>
#include <WalkRandom.hpp>
#include <approachBall.hpp>
#include <behavior.hpp>
#include <behaviorGoalie.hpp>
#include <behaviorStriker.hpp>
#include <faceBall.hpp>
#include <movingAverage.hpp>
#include <postKick.hpp>
#include <pickUp.hpp>
#include <readyTurn.hpp>
#include <readyWait.hpp>
#include <readyWalk.hpp>
#include <roundBall.hpp>
#include <sonarLeft.hpp>
#include <sonarMiddle.hpp>
#include <sonarRight.hpp>
#include <staticTest.hpp>
#include <teste.hpp>
#include <turn.hpp>
#include <walkBall.hpp>
#endif
